# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ht_gui_theme_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 260)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_edit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_edit.setObjectName("btn_edit")
        self.gridLayout.addWidget(self.btn_edit, 2, 0, 1, 1)
        self.lw_theme = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.lw_theme.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.lw_theme.setTextElideMode(QtCore.Qt.ElideRight)
        self.lw_theme.setObjectName("lw_theme")
        self.gridLayout.addWidget(self.lw_theme, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.lw_theme.setCurrentRow(-1)
        self.btn_edit.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "主题"))
        self.btn_edit.setText(_translate("Dialog", "编辑选定主题配置"))
        self.label.setText(_translate("Dialog", "可选择的主题"))
